export const PAKISTAN_BANKS = [
  // Mobile wallets / branchless banking
  "JazzCash",
  "Easypaisa",
  "NayaPay",
  "SadaPay",
  "UPaisa",
  "Zindigi (JS Bank)",
  "Konnect (HBL)",
  // Commercial banks
  "Habib Bank Limited (HBL)",
  "United Bank Limited (UBL)",
  "MCB Bank",
  "Allied Bank Limited (ABL)",
  "National Bank of Pakistan (NBP)",
  "Meezan Bank",
  "Bank Alfalah",
  "Askari Bank",
  "Faysal Bank",
  "Bank Al Habib",
  "Standard Chartered Pakistan",
  "Soneri Bank",
  "JS Bank",
  "Habib Metropolitan Bank",
  "Silk Bank",
  "Summit Bank",
  "Bank of Punjab (BOP)",
  "Bank of Khyber (BOK)",
  "Sindh Bank",
  "Al Baraka Bank Pakistan",
  "Dubai Islamic Bank Pakistan",
  "Other",
] as const;
